#!/system/bin/sh
#Headphone volume
#Change headphone volume:
#Vol 45 (default, stock)

echo 1 > /sys/class/misc/boeffla_sound/boeffla_sound
echo "45 45" > /sys/class/misc/boeffla_sound/headphone_volume

